-- Optional Supabase persistence for FinSight.
-- Keep service keys in environment variables; never commit them.
create table if not exists audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  invoice_id text,
  message text not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_events_invoice_idx on audit_events(invoice_id);
create index if not exists audit_events_created_idx on audit_events(created_at desc);

alter table audit_events enable row level security;
-- For a local/demo prototype, configure policies appropriate to your deployment.
-- Do not expose a Supabase service-role key in the browser.
