-- FinSight Supabase audit_events schema repair
-- Run this entire script in the Supabase SQL Editor.
-- It preserves existing audit rows and repairs the common legacy "ed" typo.

DO $$
BEGIN
  -- If a legacy column named "ed" exists and "id" does not, rename it.
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'audit_events' AND column_name = 'ed'
  )
  AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'audit_events' AND column_name = 'id'
  ) THEN
    ALTER TABLE public.audit_events RENAME COLUMN ed TO id;
  END IF;
END $$;

-- If neither column exists, create the expected primary key.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'audit_events' AND column_name = 'id'
  ) THEN
    ALTER TABLE public.audit_events
      ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- Ensure the expected application columns exist.
ALTER TABLE public.audit_events
  ADD COLUMN IF NOT EXISTS event_type text,
  ADD COLUMN IF NOT EXISTS invoice_id text,
  ADD COLUMN IF NOT EXISTS message text,
  ADD COLUMN IF NOT EXISTS metadata jsonb,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

-- Add a primary key only when the table currently has none.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'public'
      AND t.relname = 'audit_events'
      AND c.contype = 'p'
  ) THEN
    ALTER TABLE public.audit_events ADD PRIMARY KEY (id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS audit_events_invoice_idx ON public.audit_events(invoice_id);
CREATE INDEX IF NOT EXISTS audit_events_created_idx ON public.audit_events(created_at DESC);

-- Keep RLS enabled/disabled according to your existing policies; do not
-- change it here. Verify the final schema with:
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'audit_events'
ORDER BY ordinal_position;
